version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      monthly-batch:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "ci"
      include: "scope"
    cooldown:
      default-days: 7
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "/"
    groups:
      monthly-batch:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    cooldown:
      default-days: 7
